version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mini-crm-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./mini-crm-backend
      dockerfile: Dockerfile
    container_name: mini-crm-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/mini-crm
      - JWT_ACCESS_SECRET=changeme-access
      - JWT_REFRESH_SECRET=changeme-refresh
      - JWT_ACCESS_EXPIRES=15m
      - JWT_REFRESH_EXPIRES=7d
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./mini-crm-frontend
      dockerfile: Dockerfile
    container_name: mini-crm-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:4000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:


